// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushMsg struct {
	Op                   int32    `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Roomid               int32    `protobuf:"varint,2,opt,name=roomid,proto3" json:"roomid,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Msg                  []byte   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushMsg) Reset()         { *m = PushMsg{} }
func (m *PushMsg) String() string { return proto.CompactTextString(m) }
func (*PushMsg) ProtoMessage()    {}
func (*PushMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *PushMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushMsg.Unmarshal(m, b)
}
func (m *PushMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushMsg.Marshal(b, m, deterministic)
}
func (m *PushMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushMsg.Merge(m, src)
}
func (m *PushMsg) XXX_Size() int {
	return xxx_messageInfo_PushMsg.Size(m)
}
func (m *PushMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PushMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PushMsg proto.InternalMessageInfo

func (m *PushMsg) GetOp() int32 {
	if m != nil {
		return m.Op
	}
	return 0
}

func (m *PushMsg) GetRoomid() int32 {
	if m != nil {
		return m.Roomid
	}
	return 0
}

func (m *PushMsg) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *PushMsg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*PushMsg)(nil), "bdim.logic.PushMsg")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4a, 0x4a, 0xc9, 0xcc, 0xd5, 0xcb, 0xc9, 0x4f, 0xcf,
	0x4c, 0x56, 0x0a, 0xe7, 0x62, 0x0f, 0x28, 0x2d, 0xce, 0xf0, 0x2d, 0x4e, 0x17, 0xe2, 0xe3, 0x62,
	0xca, 0x2f, 0x90, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x2f, 0x10, 0x12, 0xe3, 0x62,
	0x2b, 0xca, 0xcf, 0xcf, 0xcd, 0x4c, 0x91, 0x60, 0x02, 0x8b, 0x41, 0x79, 0x42, 0x42, 0x5c, 0x2c,
	0xa5, 0xc5, 0xa9, 0x45, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x00, 0x17,
	0x73, 0x6e, 0x71, 0xba, 0x04, 0x8b, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x88, 0xe9, 0xc4, 0x11, 0xc5,
	0xa6, 0x67, 0x9d, 0x5e, 0x54, 0x90, 0x9c, 0xc4, 0x06, 0xb6, 0xd5, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0xec, 0x5a, 0x8f, 0xbf, 0x82, 0x00, 0x00, 0x00,
}
